version: '3'
services:
  postgres:
    container_name: ytclone-db
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yt
      POSTGRES_PASSWORD: yt
      POSTGRES_DB: yt
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432
