name: CI / Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_VERSION: 18.12.1
  PNPM_VERSION: 7.24.3

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils
        
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-


      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: format
        run: pnpm format

      - name: lint
        run: pnpm lint

      # - name: jest
      #   run: pnpm test

      - name: tsc
        run: pnpm tsc
